Chore/document scheduler
topfreegames/maestro pull request #401
Opened 2022-04-13 21:12 UTC by caiordjesus

### What?
Adds documentation for scheduler to maestro docs.
### Why?
So Maestro users are able to better understand how Maestro works, it's important to understand the scheduler, it's most important entity.

2022-04-14 17:22 UTC, arthur29 requested changes

2022-04-14 17:22 UTC, arthur29 commented on docs/Scheduler.md
> +Objectively, a **Scheduler** is 1:1 to **Kubernetes namespace** (as referenced [here](Kubernetes.md)), and contains all the information for creating
Hey @caiordjesus I think that as Kubernetes is a port only related to our runtime we should avoid relating its concepts with Maestro concepts. What do you think about describing what a Scheduler is for Maestro Next only?

2022-04-14 17:22 UTC, arthur29 commented on docs/Scheduler.md
> +The scheduler, then, is like a template for kubernetes.
Here as well

2022-04-14 17:22 UTC, arthur29 commented on docs/Scheduler.md
> +Contains vital information about the game rooms. Be aware that the spec is the most related aspect of the scheduler interacting with kubernetes.
What do you think to change kubernetes here to `Runtime` or something like that?

2022-04-18 11:45 UTC, guilhermocc commented on docs/Scheduler.md
> +These operations are responsible for creating a scheduler or newer versions, switching an active version, switch version,
"switching an active version, switch version," -> duplicated text here

2022-04-18 11:47 UTC, guilhermocc commented on docs/Scheduler.md
> +- Major version: **Replace** the game rooms.
```suggestion
- Major version: **Replace** the game rooms in a switch active version event.
```

2022-04-18 11:47 UTC, guilhermocc commented on docs/Scheduler.md
> +- Minor version: **Don't replace** game rooms.
```suggestion
- Minor version: **Don't replace** game rooms in a switch active version event.
```

2022-04-18 12:00 UTC, guilhermocc commented on docs/Scheduler.md
> +- **terminationGracePeriod**: When a game room receives the signal to be deleted, it will take this value (in milliseconds) to be completely deleted;
This is a required field? if not, what is the default value?

2022-04-18 12:00 UTC, guilhermocc commented on docs/Scheduler.md
> +more than two images;
```suggestion
more than two containers;
```

2022-04-18 12:03 UTC, guilhermocc commented on docs/Scheduler.md
> +There are, now, 3 supported formats by Maestro:
We are not explaining how each kind works, WDYT about describing it here?

2022-04-19 13:52 UTC, guilhermocc approved these changes

2022-04-19 14:52 UTC, arthur29 commented on docs/Scheduler.md
> +To directly interact with a Scheduler, the user enqueues [operations](Operations.md) using the management API.
```suggestion
To directly interact with a Scheduler, the user enqueues [operations](Operations.md) using the Management API.
```

2022-04-19 14:52 UTC, arthur29 approved these changes
LGTM

2022-04-19 17:56 UTC, merged