Add autoscaling documentation
topfreegames/maestro pull request #464
Opened 2022-06-09 12:25 UTC by guilhermocc

## What ❓ 
Add autoscaling feature documentation section.

2022-06-09 12:43 UTC, guilhermocc commented on docs/Autoscaling.md
> +```
![Uploading image.png…]()

2022-06-09 12:45 UTC, guilhermocc commented on docs/Autoscaling.md
> +|          2         |           2           |     0.9     |          20          |    Scale Up: +18    |
Preview:
![image](https://user-images.githubusercontent.com/33766735/172849968-5ff80cc6-c9a8-45b8-be3d-6419424b071b.png)

2022-06-10 12:58 UTC, caiordjesus requested changes
Update Scheduler.md to have autoscaling link, add example to example scheduler on that file also

2022-06-10 12:58 UTC, caiordjesus commented on docs/Autoscaling.md
> +    use_autoscaling[Use Autoscaling policy to calculate the desired number of rooms corced in min max range]
```suggestion
    use_autoscaling[Use Autoscaling policy to calculate the desired number of rooms coerced in min-max range]
```

2022-06-10 12:58 UTC, caiordjesus commented on docs/Autoscaling.md
> +```yaml
WDYT about adding these guys inside a dropdown like in Scheduler.md?

2022-06-10 12:58 UTC, caiordjesus commented on docs/Autoscaling.md
> +- **min** [integer]: Minimum number of rooms the scheduler should have, it must be greater than zero.
```suggestion
- **min** [integer]: Minimum number of rooms the scheduler should have, it must be greater than zero. For zero value, disable autoscaling and set "roomsReplicas" to 0.
```

2022-06-10 12:58 UTC, caiordjesus commented on docs/Autoscaling.md
> +- **min** [integer]: Minimum number of rooms the scheduler should have, it must be greater than zero.
Trust me, this information is very relevant for people rolling out the docs trying to understand how to have 0 replicas

2022-06-10 12:58 UTC, caiordjesus commented on docs/Autoscaling.md
> +```yaml
Same dropdown comment

2022-06-10 13:27 UTC, caiordjesus approved these changes

2022-06-10 13:28 UTC, merged