List operation
topfreegames/maestro pull request #503
Opened 2022-07-26 21:05 UTC by mflilian

2022-07-28 15:01 UTC, arthur29 requested changes

2022-07-28 17:01 UTC, arthur29 commented on proto/api/v1/operations.proto
> +  string per_page = 5;
I forgot to comment here that page and per_page should be `optional` parameters since they could not be sent on the request.

2022-08-01 17:27 UTC, guilhermocc commented on proto/api/v1/operations.proto
> +  optional string status = 3;
@mflilian we must rename it to `stage` now, right? maybe this PR should be rebased with https://github.com/topfreegames/maestro/pull/507

2022-08-01 19:22 UTC, arthur29 commented on proto/api/v1/operations.proto
>    repeated ListOperationItem finished_operations = 3;
Hey @mflilian what do you think to return only operations without saying which state they are in?

2022-08-02 11:58 UTC, closed without merging