Operations handler - add status validation
topfreegames/maestro pull request #507
Opened 2022-07-28 13:20 UTC by mflilian

### What :question: 

### Why 🤔

2022-07-28 15:03 UTC, arthur29 commented on internal/api/handlers/operations_handler.go
> +	}
Why did this error validation is being done after an assignment to `operation.Status`? What do you think to move it close to which it was assigned?

2022-07-28 15:07 UTC, arthur29 requested changes

2022-07-28 15:07 UTC, arthur29 commented on internal/api/handlers/operations_handler.go
> +	}
How are you planning to handle the operations on error status?

2022-07-28 15:07 UTC, arthur29 commented on proto/api/v1/operations.proto
> +  string status = 3;
AFAIK the status is not a required parameter as `page` and `per_page`, what do you think to add the `optional` parameter? This link could help you https://developers.google.com/protocol-buffers/docs/proto#optional

2022-08-01 17:21 UTC, guilhermocc commented on proto/api/v1/operations.proto
> +  // Optional parameter for enabling filter by operation status
```suggestion
  // Optional parameter for enabling filter by operation execution stage, can be one of [pending, active, history]
```

2022-08-02 13:25 UTC, closed without merging