Add pagination stage params
topfreegames/maestro pull request #511
Opened 2022-08-02 01:29 UTC by mflilian

2022-08-08 22:40 UTC, arthur29 requested changes

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/fixtures/response/operations_handler/error_listing_finished_operations.json
> +  "message": "error listing operations on history stage",
```suggestion
  "message": "error listing operations on final stage",
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/fixtures/response/operations_handler/list_operations_active_stage_success.json
> +  ]
What do you think to add here the pagination parameters to assert them on the tests?

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/fixtures/response/operations_handler/list_operations_history_stage_success.json
> +}
Two things here.

1. What do you think about renaming this file by changing `history` in favor of `final`?
2. And last but not least and the pagination response fields?

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=history", nil)
```suggestion
		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=final", nil)
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=history&order_by=createdAt asc", nil)
```suggestion
		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=final&order_by=createdAt asc", nil)
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler.go
> +	case "history":
```suggestion
	case "final":
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +	t.Run("with success and operations history stage", func(t *testing.T) {
```suggestion
	t.Run("with success and operations final stage", func(t *testing.T) {
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=history", nil)
```suggestion
		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=final", nil)
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +		responseBody, expectedResponseBody := extractBodyForComparison(t, rr.Body.Bytes(), "operations_handler/list_operations_history_stage_success.json")
Here if you agree with me on changing the name of the file you will need to update this line.

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +	t.Run("with error when listing operations in history stage", func(t *testing.T) {
```suggestion
	t.Run("with error when listing operations in final stage", func(t *testing.T) {
```

2022-08-08 22:40 UTC, arthur29 commented on internal/api/handlers/operations_handler_test.go
> +		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=history", nil)
```suggestion
		req, err := http.NewRequest(http.MethodGet, "/schedulers/zooba/operations?stage=final", nil)
```

2022-08-19 20:01 UTC, arthur29 commented on internal/api/handlers/operations_handler.go
> +	return page, pageSize, nil
Hey @mflilian the page will be extracted in human readable form, but it will be used as `array index`. Are you converting this value?

2022-08-19 21:31 UTC, guilhermocc approved these changes

2022-08-19 21:31 UTC, merged

2022-08-19 22:41 UTC, arthur29 commented on internal/api/handlers/operations_handler.go
> +	}
Hello @mflilian and @guilhermocc here I think that is more appropriate to execute math decreasing `1` from the value and after validating if the number is valid (greater or equal to 1).