Feat/store noop operations in new sorted set
topfreegames/maestro pull request #518
Opened 2022-08-17 18:59 UTC by guilhermocc

### What ❓ 
Update operations storage **_UpdateOperationStatus_** method to store no-action operations in another sorted set instead the _history_.

### Why 🤔 
We are currently including health controller operations that have no action in the operations history. With the high number of no-action health controller operations that are executed periodically, our operations listing ends up with a lot of "noise" with operations that don't really bring the information that the final user needs.

2022-08-17 19:00 UTC, guilhermocc commented on internal/adapters/operation/operation_storage_redis.go
> +
No changes here, just moved this function

2022-08-18 17:56 UTC, arthur29 requested changes

2022-08-18 17:56 UTC, arthur29 commented on internal/adapters/operation/operation_storage_redis.go
> +}
Hey @guilhermocc this is confusing me. Here the function search for `noop`, but the return is to a variable called `operationTookAction`.

2022-08-18 17:56 UTC, arthur29 commented on internal/adapters/operation/operation_storage_redis.go
> +}
And during the switch, it is tested as if `operationTookAction`

2022-08-18 18:26 UTC, arthur29 approved these changes
LGTM

2022-08-18 18:42 UTC, merged